### PR TITLE
write into $HOME of user

### PR DESCRIPTION
**Pull request by Lassulus**

### CODE REVIEW

**Comment by Gordon999** [comment]
Thanks for the suggestion but l prefer to keep the images and video seperate from /home. There can be 1000s of images captured which can make using /home very full. Using /pictures and /video makes it easy to delete etc.
You can modify the script easily to suit your request.

**Comment by Lassulus** [comment]
the old location was already in /home but in only worked if the current user was the first (in aphabetical order) in /home. the new code should be more robust and work if there are multiple users on the system

**Comment by Gordon999** [comment]
I admit I never thought of multiple users !!. I'll give it some thought.

**Comment by Gordon999** [comment]
Hopefully fixed in v3.7. Let me know if not.

**Comment by Gordon999** [comment]
Fixed

**Pull request closed without merging**
